sudo: false
language: python
python:
- '2.6'
- '2.7'
- '3.5'
- '3.6'
install:
- pip install requests
- pip install six
- pip install nose
- pip install pep8
- pip install dicttoxml
script:
- pep8 --max-line-length=180 qcloud_cos/.
- nosetests -s -v ut/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: dt3310321
  password: *********
  on:
    tags: true
    branch: master
